### ISSUE TITLE
Drucker Chemievorbereitung

### ISSUE THREAD

**Issue by menzelths** [menzelths/ESG#1]
Drucker in der Chemievorbereitung erscheint nicht in der Druckerliste.

**Comment by menzelths** [comment]
Ist laut Aussage der Chemiker ein Farbdrucker.

**Comment by efficom** [comment]
Habe Drucker umgestellt, NWT ist S/W, Chemie Farbe. Ganz genau weiß ich nicht, ob es die richtigen Geräte sind. Zuordnung sollte klappen, dann einfach mal Testseite drucken.

**Comment by menzelths** [comment]
gibt noch probleme mit dem strom in cv, teste dort alles, sobald dort alles wieder tut.

**Comment by menzelths** [comment]
drucker in chemie druckt farbig, allerdings sind s/w.- und farbeinstellung vertauscht. bitte noch ändern.

**Comment by uulmer** [comment]
Farbdrucker auf Standardwert color, S/W-Drucker auf sw eingestellt.

**Comment by menzelths** [comment]
danke
