### ISSUE TITLE
Installation der Mikroskopsoftware auf Bio-Rechnern

### ISSUE THREAD

**Issue by menzelths** [menzelths/ESG#10]
CD-ROM liegt im Fach im Sekretariat.
Bitte in Biosaal 1, 2 und in der Bio-Vorbereitung.

**Comment by uulmer** [comment]
alle 3 installiert, bitte testen
Programm benötigt einige Sekunden zum starten

**Comment by menzelths** [comment]
warte noch auf rückmeldung von bio.

**Comment by menzelths** [comment]
funktioniert!
