### ISSUE TITLE
Tausch-Verzeichnis fehlt

### ISSUE THREAD

**Issue by menzelths** [menzelths/ESG#13]
Nach der Information einer Kollegin fehlt im IR1 auf PC-05 das Tauschverzeichnis. Der selbe Schüler kann interessanterweise, an einem anderen Rechner angemeldet, auf das Verzeichnis zugreifen.

Werde Netzwerkverbindung prüfen.

**Comment by menzelths** [comment]
im ir1 scheinen die rechner pc 05, pc 06 und pc 07 tatsächlich immer wieder probleme zu machen. es gibt beim hochfahren auch die meldung von opsi, dass die verbindung zu 10.1.1.5:447 (oder was es noch eine 4 mehr?) nicht hergestellt werden kann.

**Comment by uulmer** [comment]
mit LMZ tel
Laufwerk H wird über Gruppenrichtlinien erstellt (Ordnerumleitung)
Laufwerk M: Schulkosole/Benutzer -> Mysites muss angezeigt werden, ansonsten Benutzer neu anlegen
Laufwerk T-Tausch, M-MySites und K werden über logon-Skript benutzer.vbs generiert
K zeigt nach Sharepoint

**Comment by uulmer** [comment]
kontrolliert: alle clients haben den paedML-school-client installiert
bitte Testen -> falls Probleme: bitte PC-Name und Datum/Uhrzeit aufschreiben
PS: Einstellungen "leere Laufwerk anzeigen" noch nicht gesetzt

**Comment by menzelths** [comment]
scheint soweit zu funktionieren.
