### ISSUE TITLE
Software in Physik und NWT 

### ISSUE THREAD

**Issue by menzelths** [menzelths/ESG#14]
Bitte die folgende Software installieren:

- CASSY
- Datastudio (auch auf den normalen Schulrechner)
- Dorn-Bader Kursstufe 11/12, Mittelstufe
- Quantenphysik Klett-Verlag

**Comment by menzelths** [comment]
CD-ROM von CASSY mit Lizenzkey in eurem Fach.
Das ist die neueste Version, Herr Schmidt wünscht sich auch noch vorerst eine Parallelinstallation mit der alten Version, bis sichergestellt ist, dass die alten Dateien von der neuen Version alle gelesen werden können.

**Comment by uulmer** [comment]
Physik-Ordner ist auf dem K-Laufwerk
LE hatte schon Cassy und Datastudio inst.

**Comment by uulmer** [comment]
bitte testen

**Comment by menzelths** [comment]
cassy hat funktioniert, physik-programme auch problemlos.
datastudio wurde noch nicht überprüft. bei problemen wird eine neues ticket erstellt.
