### ISSUE TITLE
Software im Werkraum

### ISSUE THREAD

**Issue by menzelths** [menzelths/ESG#15]
Bitte die folgende Software auf den Lehrerrechner im Technikraum:

- Datastudio
- GLX-Simulator (zum Anschließen des GLX-Explorer)

**Comment by efficom** [comment]
Und wo noch überall? Ich habe jetzt mal ein OPSI-Paket gemacht, das ist auf den Rechnern im IR1, Physikbereich und NWT ebenfalls verteilt.
