### ISSUE TITLE
Farblaserdrucker Raum 106 (PV)

### ISSUE THREAD

**Issue by menzelths** [menzelths/ESG#17]
Laut Herrn Schmidt nur Monotondruck möglich, auch wenn in der Druckerauswahl der Farbdrucker gewählt ist.

**Comment by efficom** [comment]
Ich habe gestern vom Server aus Testausdrucke gemacht, die waren beide ok, Farbe bei col, schwarzweiß bei sw. Werde morgen noch mal direkt am Client testen.

**Comment by menzelths** [comment]
hat es funktioniert?

**Comment by menzelths** [comment]
problem behoben.
