### ISSUE TITLE
Sound in IR1

### ISSUE THREAD

**Issue by menzelths** [menzelths/ESG#19]
Herr Keller meldet: 
im IR1: PC 02, 08, 18 und 19 haben entweder keine Soundkarte oder sie ist nicht installiert.

**Comment by uulmer** [comment]
es geht um Kopfhörer - nicht um Sound über Monitor

**Comment by efficom** [comment]
Habe ich mit Soundkabel am vorderen Soundausgang und den Monitorsprechern getestet.
PC-08 ok, PC-02 ok, PC-18 und PC-19 mussten erst was installieren
Grrundsätzlich kommt das Realtek-Hilfsprogramm, das vorschlägt, was da angeschlossen wird. Es hilft, sein Hirn ein wenig einzuschalten und zu lesen, was da steht. Wenn nix eingesteckt ist, zeigt das Programm keine Wiedergabegeräte an. Funktioniert auch als einfacher User problemlos. Vielleicht hatten die Kopfhörer was, würde ich nicht ausschließen. 
Schüler egal welchen Alters sind leider ziemlich grobmotorisch veranlagt. Das halten manche Sachen nicht aus. Ich hatte übrigens wieder mehrere Tastaturen, wo die Tasten so verkehrt eingedrückt waren, dass sie den kompletten Bootvorgang blockiert haben. Wir sollten das Thema mit der Benutzerordnung dringend angehen, dieses Fehlerprovozieren geht einfach nicht.

**Comment by menzelths** [comment]
ok, danke
