### ISSUE TITLE
WLAN für Lehrer in Lehrerzimmer, NWT

### ISSUE THREAD

**Issue by uulmer** [menzelths/ESG#20]
über Proxy und bei SSL mit Zertifikat installieren oder getrennt und mit VLAN/extra Leitungen

**Comment by menzelths** [comment]
nicht ganz klar, was muss ich tun?

**Comment by uulmer** [comment]
Variante  1 machen


Variante 1: Extra WLAN mit extra Kabel zwischen Lehrerzimmer, Musik etc
    Vorteil: Keine Proxy-Einstellungen
    Nachteil: kein direkter Zugriff auf das Schulnetz
    Voraussetzung: Kabel müssen vorhanden sein

Variante 2:
    WLAN über Schulnetz
    Vorteil: Zugriff auf Schulnetz möglich
    Nachteil: Proxy muss konfiguriert werden
    Nachteil: Firewalleinstellungen müssen evtl. konfiguriert werden
    Vorteil: keine extra Kabel/VLANs nötig

**Comment by efficom** [comment]
Gleiches gilt ja für Kursraum K4. Wir sollten ein neues Passwort festlegen oder sollen wir das alte vom Lehrerzimmer benutzen?
AccessPoint im K4 ist abgebaut und muss neu eingestellt werden. Dazu bitte PW mitteilen.

**Comment by efficom** [comment]
Ist fertig, da gab es einen weiteren Threat. Dort steht alles drin.
