### ISSUE TITLE
vlc

### ISSUE THREAD

**Issue by menzelths** [menzelths/ESG#23]
-  bitte vlc überall und für alle auf den desktop oder in die taskleiste legen
- kann man den vlc als standardprogramm festlegen, das gestartet wird, wenn eine dvd ins laufwerk gelegt wird?

**Comment by efficom** [comment]
VLC liegt in der Taskleiste für Schüler und Lehrer. Kannst DU mir eine Tests-DVD hinliegen? GGf. muss man das noch testen.

**Comment by menzelths** [comment]
danke, funktioniert

**Comment by menzelths** [comment]
vlc fehlt noch in k4.

bitte wirklich in allen räumen installieren und in allen räumen in die taskleiste.

**Comment by uulmer** [comment]
auf k4, lar pc2,3,4 auf "beim nächsten Start installieren" gesetzt
IR2auch ?? (bis jetzt noch nicht)

**Comment by uulmer** [comment]
ist auf allen PCs installiert, auch im IR2, Ausnahme K4
K4 sollte vlc beim nächsten Start installieren

**Comment by menzelths** [comment]
vielen dank!
