### ISSUE TITLE
Aufkleber Laptops NWT

### ISSUE THREAD

**Issue by menzelths** [menzelths/ESG#24]
Bitte Aufkleber an die echten Rechnernamen anpassen. Das "-W7" wird ja nicht mehr benötigt.

Gibt sonst für Kollegen Probleme mit der lokalen Anmeldung.

**Comment by efficom** [comment]
Habe ich angepasst.

**Comment by efficom** [comment]
Und noch die Beschriftung für den lokalen ESGUser ergänzt, wo es gefehlt hat.
