### ISSUE TITLE
D-GISS Verknüpfung

### ISSUE THREAD

**Issue by menzelths** [menzelths/ESG#25]
installation in chemie funktioniert nicht mehr: ging nur ein mal, solange die kollegin angemeldet war, beim nächsten mal schon nicht mehr. 

hohe priorität, da so kein unterricht in chemie stattfinden kann!

problem: 
die alten dateien werden durch doppelklick nicht mit dem neuen programm geöffnet. und aus dem neuen programm heraus besteht keine möglichkeit, die alten dateien zu öffnen.

**Comment by menzelths** [comment]
problem: wenn man versucht, eine alte datenbank-datei mit dem neuen programm zu öffnen, so scheinen hart kodierte pfade nötig zu sein, da die datenbankbezeichnung immer das jahr der aktuellen version enthält. eventuell über änderung der bezeichnungen der datenbanken zu lösen.

**Comment by efficom** [comment]
Habe D-Giss getestet. Wenn man auf Datenbank - D-GISS-Datenbank klickt, dauert es eine Zeit, bis die D-GISS-Datenbank im Access 2013 geöffnet wird. Wichtig ist das Bestätigen der Sicherheitseinstellungen, sonst darf und kann man gar nichts machen. Dann lassen sich die D-GISS-Menüs entsprechend nutzen. Ich denke, es ist nicht vor gesehen, mit einer D-GISS 2015-Version noch einer 2014er-Datenbank zu öffnen. Anders kann ich mir das nicht erklären, dass hier keine Auswahlmöglichkeiten bestehen.
