### ISSUE TITLE
WLAN Lehrer in neuen Räumen funktioniert nicht

### ISSUE THREAD

**Issue by menzelths** [menzelths/ESG#27]
Mehrfache Versuche, sich anzumelden, sind gescheitert. Auch nach Änderung des Passworts keine Besserung. Bitte überprüfen!

**Comment by efficom** [comment]
Komme ich erst in den Ferien dazu. Wie habt Ihr das gemacht? Mit den NWT-Notebooks? Mit welchen Geräten? Schuleigene Geräte müssen sich am Schul-WLAN anmelden bzw. bekommen das Netz automatisch.

**Comment by efficom** [comment]
WLAN für Lehrer ist jetzt fertig. Ich habe das WLAN-PW für Octogate noch mal überschrieben. Das WLAN heißt jetzt überall 'Schule_Lehrer', es läuft also im neuen Gebäude, im LZ und in den Kursräumen, wobei die letzten beiden Netze internettechnisch über den T@School-Anschluss verbunden sind.
Das PW schicke ich Dir per WhatsApp kommentarlos, einen Aushang mit dem Hinweis auf das neue Netz habe ich auch gemacht.
