### ISSUE TITLE
Beamer GS2 flackert

### ISSUE THREAD

**Issue by menzelths** [menzelths/ESG#28]
Laut Bericht der Kollegen aber nur bei angeschlossenem PC.

**Comment by menzelths** [comment]
wurde überprüft: liegt an netzwerkkabel. bitte (besser bageschirmten?) kabeltyp dort installieren.

**Comment by efficom** [comment]
Ich habe das jetzt geprüft und verschiedene Tests durchgeführt. Es ist ein Potentialproblem, das beim Deaktivieren des LAN-Anschlusses nicht mehr auftritt. Dann ist das Flackern weg.
Die Lösung liegt im Nutzen eines ungeschirmten Kabels ohne Metallkontakte, dann werden die Störungen auf der LAN-Verbindung nicht in den Rechner übertragen. Das Lautsprecherbrummen ist jetzt auch weg.
