### ISSUE TITLE
Laptop Deutsch Passwort und Acrobat Reader

### ISSUE THREAD

**Issue by menzelths** [menzelths/ESG#29]
Bitte neues Passwort für lokalen User einrichten und entsprechend beschriften.

Bitte auch den Acrobat Reader installieren.

Laptop befindet sich bei Fr. Held im Schrank.

**Comment by menzelths** [comment]
Laptop befindet sich auf meinem Platz im LZ (ist der Laptop in der hellen Husse)

**Comment by efficom** [comment]
Muss komplett neu installiert werden. Es erstaunt mich, wie lange manche Leute brauchen, um das Gerät zur Installation abzugeben.

**Comment by efficom** [comment]
Installation läuft, erster Teil ist abgeschlossen. Der dauert noch einige Zeit. Ist vermutlich am Montag fertig.

**Comment by efficom** [comment]
Lokale Benutzer noch angelegt und beschriftet. Ist wie bei NWT. Liegt auf Deinem Platz.
