### ISSUE TITLE
Audacity

### ISSUE THREAD

**Issue by menzelths** [menzelths/ESG#3]
Benötigen Audacity im IR1 und in NWT / Physik.

**Comment by uulmer** [comment]
ist im IR1 schon verteilt
habe auf NWT auf angefordert gesetzt, wird beim nächsten Rechnerstart installiert

**Comment by menzelths** [comment]
laptops im nwt-raum sind aufgebaut.

**Comment by uulmer** [comment]
dann müsste dort WoL tun, reagiert aber nicht (soweit aus der Ferne beobachtbar)
-> WoL-Einstellungen bei NWT-Geräten im BIOS kontrollieren

**Comment by efficom** [comment]
Thomas, bitte kontrolliere mal, ob die Teile Strom haben. Wenn der Hauptschalter aus ist, laufen die Akkus leer. Zur Not kannst Du vielleicht auch überall das Startknöpfchen drücken, geht schnell, weil die alle beieinander stehen:-).
Danke!

**Comment by menzelths** [comment]
gestern an zwei geräten getestet, einmal auch nach neustart.
programm ist auf den rechnern installiert, scheint aber nicht zu starten.

**Comment by menzelths** [comment]
gerade im ir1 getestet: geht auf den schülerrechnern, aber NICHT auf dem lehrerrechner

**Comment by uulmer** [comment]
sieht nach 32bit-Problem aus
startet auf 32bist systemen als Administrator, sonst nicht (an 2 PCs festgestellt)

**Comment by uulmer** [comment]
Startskript zur Änderung der Berechtigungen erstellt

**Comment by menzelths** [comment]
Scheint soweit zu funktionieren. Habe keine negative Rückmeldung mehr bekommen. Sonst wird das Ticket nochmal geöffnet.
