### ISSUE TITLE
Installation Software für die Dokumentenkamera (Epson) in Physik und Bio

### ISSUE THREAD

**Issue by menzelths** [menzelths/ESG#31]
Die Kamera ist ohne die Software leider nicht zu nutzen.

**Comment by efficom** [comment]
Kameras in der Physik und Biologie kann ich nicht finden. USB-Schluss. Bitte bereit stellen, sonst kann ich nichts installieren, habe auch keine Treiber o.ä.. Anschluss wie? USB?

**Comment by efficom** [comment]
Treiber ist installiert, allerdings reicht reine USB-Verbindung vermutlich nicht aus. Ebenso fehlt eine Kamera-Video-Software. Im Download-Bereich bei Epson kann man dazu nichts herunter geladen. Wie ist die Funktion gedacht? Ich habe keine Video/VGA-Kabel o.ä. zu der Kamera gefunden.

**Comment by menzelths** [comment]
Gibt es schon Neuigkeiten bezüglich der Arcsoft-Software für die Kamera?

**Comment by menzelths** [comment]
Danke
