### ISSUE TITLE
Vertrauensstellung IR1

### ISSUE THREAD

**Issue by menzelths** [menzelths/ESG#33]
PC-04 und PC-08 haben keine Vertrauensstellung. Zeitpunkt: 18.12.2015 um 10h10.

**Comment by efficom** [comment]
Habe ich getestet und korrigiert.
Auf Deinem AP lag noch ein Zettel mit folgenden Punkten:
IR1-PC-01: kein Word, konnte ich nicht nachvollziehen, sowohl als Schüler als auch als Lehrer war Word zu starten
IR1-PC-05: Kein Tauschverzeichnis. War ebenfalls beides Mal vorhanden. Muss ein Benutzerproblem sein.
IR1-PC-06: Bildschirm funktioniert nicht. Die Schalter haben so langsam Ihre Probleme durch das dauernde Ein- und Ausschalten. ich plädiere dazu, die Monitore auf Standby zu lassen, damit umgehen wir das Problem, auch wenn es ein wenig Strom kostet.
