### ISSUE TITLE
Laptops NWT

### ISSUE THREAD

**Issue by menzelths** [menzelths/ESG#34]
NB 08  Rechner startet nicht.

des weiteren:
auf meinem Platz (von Herrn Wagner hingelegt) liegen zwei weitere Laptops
- auf einem nach Anmeldung kein Home-Verzeichnis auffindbar
- auf dem anderen will der Laptop ständig Programme installieren, wird aber nie fertig

**Comment by efficom** [comment]
NB-09: Da gab es einen Fehler mit DataStudio, ist korrigiert, tut jetzt richtig. NB-17: Ich habe mich mit dem Schüler-Testaccount 'test2' mit Passwort 'test' angemeldet. War problemlos mit dem Profil. Denke, dass das Schülerprofil einen Schuss hat. Vielleicht löschen und neu anlegen?
