### ISSUE TITLE
Lehrer-Rechner NWT-Raum nur temporäres Profil

### ISSUE THREAD

**Issue by menzelths** [menzelths/ESG#35]
Bei der Anmeldung wird nur ein temporäres Profil geladen, ging vor zwei Tagen noch problemlos.

**Comment by efficom** [comment]
Habe ich probiert mit zwei Usern, ging ohne Probleme. Lehrer soll das an anderen Rechnern prüfen, damit wir die Fehlerquelle besser verifizieren können.
Kann nicht sagen, warum es manchmal Profilprobleme gibt beim Anmelden.
