### ISSUE TITLE
Bio-Lehrerrechner

### ISSUE THREAD

**Issue by menzelths** [menzelths/ESG#38]
Meldung: zu wenig Speicher, startet im abgesicherten Modus, dadurch dort kein Internet verfügbar.

**Comment by efficom** [comment]
Ist das Biosaal 1? Dort ist nur eine kleine SSD eingebaut. Habe die Partitionsgrenzen verändert. Dadurch stehe jetzt 50GB als Laufwerk C zur Verfügung.
