### ISSUE TITLE
Test WLAN

### ISSUE THREAD

**Issue by efficom** [menzelths/ESG#4]
Ich werde am Freitag mit meinen Schülern das WLAN im neuen Gebäude testen. Dazu bekommt jeder eines der Schullaptops und soll sich damit mal internettechnisch "austoben". Ich denke, so können wir uns ein reales Feedback über die gleichzeitige Nutzung mehrerer Systeme über WLAN erarbeiten.

**Comment by menzelths** [comment]
hat soweit funktioniert, oder? können wir den thread schließen?

**Comment by efficom** [comment]
Ja, hat gepasst. Die Lehrer sollten drauf achten, dass das WLAN aktiviert ist. War manchmal aus.
