### ISSUE TITLE
Software für WLAN Oszilloskop installieren

### ISSUE THREAD

**Issue by menzelths** [menzelths/ESG#44]
Bitte auf Laptops in Physik die Software für Vellemann WFS 210 installieren.
Hier die Downloadseite: 
https://www.velleman.eu/support/downloads/?code=WFS210

**Comment by efficom** [comment]
Paket ist vorbereitet und im Physikbereich und auf den NWT-Notebooks installiert.
Bitte prüfen, ob Treiber bereits im Softwarepaket integriert ist. Das ging aus dem Installationspaket nicht genau hervor.
