### ISSUE TITLE
Installation von musescore 2 im Musiksaal und im IR1 und IR2

### ISSUE THREAD

**Issue by menzelths** [menzelths/ESG#45]
Bitte installieren: ist ein Programm zur Noteneingabe in Musik!

Hier die Homepage:

https://musescore.org/de

**Comment by efficom** [comment]
Wo soll das installiert werden? Musikbereich und IR1?

**Comment by menzelths** [comment]
Siehe Überschrift :-)

**Comment by efficom** [comment]
Paket ist generiert und verteilt, bitte testen.
