### ISSUE TITLE
benutzer ohne home-verzeichnis

### ISSUE THREAD

**Issue by menzelths** [menzelths/ESG#5]
die Benutzerin a.tsoulopoulos hat kein Homeverzeichnis. in nwt hat anscheinend alles funktioniert, jetzt nicht mehr. an zwei rechnern im ir1 getestet. alle anderen schüler der 10b hatten kein Problem.

Schülerin kann so nicht am pc arbeiten.

ist der lange Name ein Problem?

**Comment by uulmer** [comment]
Es gibt längere Anmeldenamen, falls der zu lange -> wird vom System verkürzt
Wahrscheinlich ist beim Anlegen des Benutzers was falsch gelaufen.
Abhilfe: Daten des Benutzers (falls vorhanden) sichern; Benutzer löschen, Benutzer unter deaktivierten Benutzern löschen; evtl. kurz warten; Benutzer neu anlegen

**Comment by menzelths** [comment]
der vollständigkeit halber hier noch der vorschlag vom lmz:


- lassen Sie den Benutzer sich nochmals am Client anmelden, so dass er seine Daten vom 
  M.-Laufwerk (das liegt auf dem Sharepoint) auf einen Stick sichern kann

- melden Sie sich am Server SP01 als Administrator an
- löschen Sie den Schüler aus den aktiven Schülern
- löschen Sie den Schüler nun auch den deaktivierten Schülern
- warten Sie ca. 1/4 Stunde (der Sharepoint ist manchmal etwas langsam)
- legen Sie den Schüler neu an
  warten Sie wieder ein paar Minuten
- testen Sie am Client, ob die Anmeldung funktioniert und der Schüler seine
  Verzeichnisse bekommt.

**Comment by menzelths** [comment]
ok
