### ISSUE TITLE
Schriftproblem IR2

### ISSUE THREAD

**Issue by menzelths** [menzelths/ESG#50]
Schriftbild ist zwischenzeitlich in allen Anwendungen NICHT lesbar. Sieht aus, wie ein zu stark komprimiertes Bild. Lutz hat ein Foto davon bekommen.

BItte beheben!

**Comment by efficom** [comment]
Das Problem hängt laut Recherche am Browser. Da es aber nur auf den virtuellen Terminals auftritt, denke ich an einen Zusammenhang mit dieser Lösung.
Da die Performance grundsätzlich leidet, bereiten wir einen Testserver vor, der Clients unter Hyper-V ansteuert, so wie das im alten Schulnetz funktioniert hat, weil es momentan nicht klar ist, wo der Engpass sitzt. Fortsetzung folgt...

**Comment by efficom** [comment]
Installation des neuen Raumes ist fertig, sollten alle pakettechnisch gleich sein, da habe ich heute noch mal Zeit investiert. Ich schreibe noch eine Mitteilung und hefte diese ans LZ und an die Tür vom IR2.
