### ISSUE TITLE
Beamer in Biosaal 1

### ISSUE THREAD

**Issue by menzelths** [menzelths/ESG#53]
Seit kurzer Zeit treten seltsame Bildstörungen auf: in jeder Zeile werden Pixel mit falscher Farbe angezeigt.

Bitte Problem beheben.

**Comment by efficom** [comment]
Habe Bildschirmanzeige getestet, empfohlene Auflösung ist 1920x1080, was in meinen Augen relativ groß ist und zu einer etwas unscharfen Anzeige führt.
Konnte den Fehler nicht nachvollziehen, vielleicht Kabel-/Anschlussproblem?
Über die Intel-eigene Anzeigesoftware rechts unten neben der Uhr (Symbol Intel HD-Grafik) lassen sich auch als einfacher User die Grafikeinstellungen ändern. Über "rechte Maustaste" auf das Symbol und dann "Grafikeigenschaften - Erweiterter Modus kann man die Auflösung auf 1680 x 1050 Pixel runter schrauben.
Dann sind die Symbole und Schriftgrößen etwas besser. Allerdings lässt sich das nicht von zentraler Stelle aus steuern wegen der zentralen Benutzerprofile und der Tatsache, dass Windows die hohe Auflösung eigentlich ok findet und deshalb diese automatisch einstellt.
