### ISSUE TITLE
Dropbox neu installieren in der Verwaltung

### ISSUE THREAD

**Issue by menzelths** [menzelths/ESG#54]
Die Aktualisierung von Dropbox schlägt fehl, da es wohl einen neuen Client gibt. Deswegen wird unser Vertretungsplan auch nicht mehr angezeigt. 
Scheinbar sind ein paar Ports nicht offen, so dass die manuell angestoßene Installation nicht abläuft.
Vielleicht hilft

https://www.dropbox.com/de/help/23

Davon betroffen sind die Rechner von Frau Legueil und von Frau Held.

HOHE PRIORITÄT!

**Comment by menzelths** [comment]
ist erledigt, vielen Dank!

**Comment by menzelths** [comment]
Funktioniert doch noch nicht: laut Frau Held hat der Client immer noch Probleme und bringt die gleiche Fehlermeldung wie bisher.

**Comment by efficom** [comment]
Erledigt, scheint zu synchronisieren. Aktuelle Version ist 3.20.1.
