### ISSUE TITLE
Dokumentenkamera PS1

### ISSUE THREAD

**Issue by menzelths** [menzelths/ESG#56]
Die Software für die Dokumentenkamera im PS1 scheint nicht installiert zu sein. Ist dieselbe wie in Bio. Bitte Installation noch nachholen.

**Comment by efficom** [comment]
Treiber war schon installiert, allerdings kann man das Gerät über VLC nicht wiedergeben, da muss es schon eine spezielle EPSON-Software geben. Muss ich noch suchen.

**Comment by efficom** [comment]
Habe CD aus BIO-Bereich geholt und auf Server kopiert. Software tut jetzt auf dem PS1-PC-01.
