### ISSUE TITLE
office als standardprogramm und startmeldungen

### ISSUE THREAD

**Issue by menzelths** [menzelths/ESG#6]
statt ms office wird bei docx- und powerpoint-dateien zur zeit noch libreoffice gestartet. 
außerdem wird beim start von ms office immer gefragt, ob die empfohlenen einstellungen übernommen werden sollen oder nicht. auswahl scheint nicht gespeichert zu werden, weshalb die frage bei jedem start von ms office kommt.

**Comment by uulmer** [comment]
könnte evtl. über Profil gelöst werden

**Comment by menzelths** [comment]
bitte problem beheben: man muss 5 fenster schließen, ehe man in word schreiben kann.
ziel: 0 fenster!

**Comment by efficom** [comment]
Habe ich über das Profil für Lehrer und Schüler umgestellt, bitte testen.

**Comment by menzelths** [comment]
Immer noch 3 Fenster zum Wegklicken vor dem Schreiben eines Textes in Word:

1. Standardprogramm: bitte legt MS Office als Standardprogramm für docx-Dateien, xlsx-Dateien, etc. fest
2. Irgendeine Abfrage zu übliche Einstellungen
3. Langweilige Tour durch die Vorzüge vom neuen Office

**Comment by menzelths** [comment]
ok, danke, mein fehler: hatte es als administrator getestet und der hat wohl ein anderes profil!
