### ISSUE TITLE
Computer IR2

### ISSUE THREAD

**Issue by menzelths** [menzelths/ESG#7]
IR2 noch nicht einsatzbereit. Regelmäßiger Unterricht wöchentlich davon betroffen.

**Comment by uulmer** [comment]
Englisch Workbook2 hat blockiert, bitte Raum testen

**Comment by uulmer** [comment]
bei vielen PCs waqr die Installation des Schul-Clients fehlerhaft, nochmals auf Setup gestellt

**Comment by uulmer** [comment]
bei einem PC kam die Fehlermeldung .Net 4 fehlt, obwohl laut opsi vorhanden

**Comment by uulmer** [comment]
paedML-Client war bei vielen Arbeitsstationen nicht installiert, bei allen ist der jetzt nstalliert (.Net 4- Fehlermeldung)
bitte jetzt nochmals testen

**Comment by menzelths** [comment]
gestern eine stunde gehalten: alle schüler hatten home- und tauschverzeichnis, anmeldung bei allen möglich. geschwindigkeit soweit in ordnung, allerdings nur editor und browser genutzt.

gebe den raum jetzt für die kollegen frei.
