### ISSUE TITLE
Drucker kann nur ein Exemplar drucken

### ISSUE THREAD

**Issue by uulmer** [menzelths/ESG#8]
in Physik-Vorbereitung, Kyocera FS-c2126
liegt an Druckerspeicher (vorhanden vs. erkannt)

Abhilfe: Druckerkonfigurationsseiten ausdrucken
Im Windows-Druckertreiber Werte hierzu einstellen

**Comment by uulmer** [comment]
Physik Vorbereitung: Drucker zusätzlich mit KX-Treiber installiert. Bitte testen, ob der Ausdruck mehrer Exemplare mit diesem Treiber funktioniert.

**Comment by efficom** [comment]
Neue KX-Treiber sind installiert, für alle Drucker. Bitte testen.

**Comment by menzelths** [comment]
problem behoben, danke!
