### ISSUE TITLE
Java in Physik fehlt

### ISSUE THREAD

**Issue by menzelths** [menzelths/ESG#9]
für den physik-unterricht wäre der einsatz von java zum zeigen von applets hilfreich. bitte entsprechendes plugin installieren.

**Comment by uulmer** [comment]
Java ist laut Paketverteilung im Physikbereich installiert.
Geht es um die Ausnahme-Seiten wie walter-fendt.de ?
Über welche Webbrowser wird die Seite aufgerufen?

**Comment by menzelths** [comment]
Ja, wieder Walter fendt. Browser meistens chrome.

**Comment by uulmer** [comment]
Java-Ausnahmen über Gruppenrichtlinie in der ganzen Schule verteilt, wird nach PC-Neustart aktiv.
tut mit IE, sollte mir Firefox tun, tut nicht mit Chrome, da Chrome kein NAPI mehr unterstützt.
Bei Chrome kann html5 verwendet werden

**Comment by menzelths** [comment]
funktioniert in firefox. vielen dank!
